### ISSUE TITLE
ConnectionResetError

### ISSUE THREAD

**Issue by anselal** [Ext-Creators/discord-ext-ipc#41]
After a while the connection closes and I get an `ConnectionResetError: Cannot write to closing transport` error on my console and on quart webpage I get an `guild_count	{'error': 'IPC Server Unreachable, restart client process.', 'code': 500}` error

**Comment by shayypy** [comment]
It tells you what to do - "restart client process". Your server process stopped so you need to reconnect your client respectively

**Comment by anselal** [comment]
Actually me server process didn't stop, unless there is an error with the library.

**Comment by anselal** [comment]
I think this has been fixed in the latest version.
It should has been marked as closed with that commit

**Comment by jgayfer** [comment]
I am still experiencing this issue on `2.1.1` when I need to restart my server.
